BookingWebApp/BookingWebApp/Controllers/HotelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookingWebApp.Models;
using PagedList;

namespace BookingWebApp.Controllers
{
    public class HotelController : Controller
    {
        private Entities7 db = new Entities7();

        // GET: Hotel
   
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
          //  ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
           
            var h_hotel = db.h_hotel.Include(h => h.d_destination).Include(h => h.ho_host);
            
            if (searchString != null)
            {
               
                page = 1;
            }
            else { searchString = currentFilter; }
            ViewBag.CurrentFilter = searchString;

            //var hotels = from h in db.h_hotel
            //             select h;
            if (!String.IsNullOrEmpty(searchString)) { h_hotel = h_hotel.Where(h => h.h_name.ToUpper().Contains(searchString.ToUpper())); }

            switch (sortOrder)
            {
                case "name_desc":
                    h_hotel = h_hotel.OrderByDescending(s => s.h_name);
                    break;
               
                
                default: // Name ascending
                    h_hotel = h_hotel.OrderBy(s => s.h_name);
                    break;
            }

            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(h_hotel.ToPagedList(pageNumber, pageSize));
        }

        // GET: Hotel/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            h_hotel h_hotel = db.h_hotel.Find(id);
            if (h_hotel == null)
            {
                return HttpNotFound();
            }
            return View(h_hotel);
        }

        // GET: Hotel/Create
        public ActionResult Create()
        {
            ViewBag.h_d_city = new SelectList(db.d_destination, "d_city", "d_city");
            ViewBag.h_ho_host = new SelectList(db.ho_host, "ho_hostname", "ho_firstname");
            return View();
        }

        // POST: Hotel/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "h_hotelid,h_name,h_stars,h_address,h_zip,h_d_city,h_description,h_d_country,h_ho_host")] h_hotel h_hotel)
        {
            if (ModelState.IsValid)
            {
                db.h_hotel.Add(h_hotel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.h_d_city = new SelectList(db.d_destination, "d_city", "d_city", h_hotel.h_d_city);
            ViewBag.h_ho_host = new SelectList(db.ho_host, "ho_hostname", "ho_firstname", h_hotel.h_ho_host);
            return View(h_hotel);
        }

        // GET: Hotel/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            h_hotel h_hotel = db.h_hotel.Find(id);
            if (h_hotel == null)
            {
                return HttpNotFound();
            }
            ViewBag.h_d_city = new SelectList(db.d_destination, "d_city", "d_city", h_hotel.h_d_city);
            ViewBag.h_ho_host = new SelectList(db.ho_host, "ho_hostname", "ho_firstname", h_hotel.h_ho_host);
            return View(h_hotel);
        }

        // POST: Hotel/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "h_hotelid,h_name,h_stars,h_address,h_zip,h_d_city,h_description,h_d_country,h_ho_host")] h_hotel h_hotel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(h_hotel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.h_d_city = new SelectList(db.d_destination, "d_city", "d_city", h_hotel.h_d_city);
            ViewBag.h_ho_host = new SelectList(db.ho_host, "ho_hostname", "ho_firstname", h_hotel.h_ho_host);
            return View(h_hotel);
        }

        // GET: Hotel/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            h_hotel h_hotel = db.h_hotel.Find(id);
            if (h_hotel == null)
            {
                return HttpNotFound();
            }
            return View(h_hotel);
        }


        // POST: Hotel/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            h_hotel h_hotel = db.h_hotel.Find(id);
            db.h_hotel.Remove(h_hotel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BookingWebApp/BookingWebApp/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookingWebApp.Models;

namespace BookingWebApp.Controllers
{
    public class RoomController : Controller
    {
        private Entities7 db = new Entities7();

        // GET: Room
        public ActionResult Index(string hotelFilter, string roomFilter)
        {
            var r_room = db.r_room.Include(r => r.h_hotel).Include(r => r.tr_typeOfRoom);
            if (hotelFilter != null && hotelFilter != "")
                r_room = r_room.Where(r => r.h_hotel.h_name == hotelFilter);
            if (roomFilter != null && roomFilter != "")
                r_room = r_room.Where(r => r.r_tr_typeOfRoom== roomFilter);

            ViewBag.hotelFilter = new SelectList(db.h_hotel, "h_name", "h_name");
        
            ViewBag.roomFilter = new SelectList(db.tr_typeOfRoom, "tr_type", "tr_type");
            return View(r_room.ToList());
        }

        // GET: Room/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            r_room r_room = db.r_room.Find(id);
            if (r_room == null)
            {
                return HttpNotFound();
            }
            return View(r_room);
        }

        // GET: Room/Create
        public ActionResult Create()
        {
            ViewBag.r_h_hotel = new SelectList(db.h_hotel, "h_hotelid", "h_name");
            ViewBag.r_tr_typeOfRoom = new SelectList(db.tr_typeOfRoom, "tr_type", "tr_type");
            return View();
        }

        // POST: Room/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "r_number,r_h_hotel,r_beds,r_price,r_description,r_tr_typeOfRoom")] r_room r_room)
        {
            if (ModelState.IsValid)
            {
                db.r_room.Add(r_room);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.r_h_hotel = new SelectList(db.h_hotel, "h_hotelid", "h_name", r_room.r_h_hotel);
            ViewBag.r_tr_typeOfRoom = new SelectList(db.tr_typeOfRoom, "tr_type", "tr_type", r_room.r_tr_typeOfRoom);
            return View(r_room);
        }

        // GET: Room/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            r_room r_room = db.r_room.Find(id);
            if (r_room == null)
            {
                return HttpNotFound();
            }
            ViewBag.r_h_hotel = new SelectList(db.h_hotel, "h_hotelid", "h_name", r_room.r_h_hotel);
            ViewBag.r_tr_typeOfRoom = new SelectList(db.tr_typeOfRoom, "tr_type", "tr_type", r_room.r_tr_typeOfRoom);
            return View(r_room);
        }

        // POST: Room/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "r_number,r_h_hotel,r_beds,r_price,r_description,r_tr_typeOfRoom")] r_room r_room)
        {
            if (ModelState.IsValid)
            {
                db.Entry(r_room).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.r_h_hotel = new SelectList(db.h_hotel, "h_hotelid", "h_name", r_room.r_h_hotel);
            ViewBag.r_tr_typeOfRoom = new SelectList(db.tr_typeOfRoom, "tr_type", "tr_type", r_room.r_tr_typeOfRoom);
            return View(r_room);
        }

        // GET: Room/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            r_room r_room = db.r_room.Find(id);
            if (r_room == null)
            {
                return HttpNotFound();
            }
            return View(r_room);
        }

        // POST: Room/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            r_room r_room = db.r_room.Find(id);
            db.r_room.Remove(r_room);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BookingWebApp/BookingWebApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookingWebApp.Models;
using PagedList;

namespace BookingWebApp.Controllers
{
    public class UserController : Controller
    {
        private Entities7 db = new Entities7();

        // GET: User
        [Authorize]
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)

        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";


            var users = db.u_user.Include(u => u.ra_rating);


            if (searchString != null)
            {

                page = 1;
            }
            else { searchString = currentFilter; }
            ViewBag.CurrentFilter = searchString;

            //var hotels = from h in db.h_hotel
            //             select h;
            if (!String.IsNullOrEmpty(searchString)) { users = users.Where(h => h.u_firstName.ToUpper().Contains(searchString.ToUpper())); }

            switch (sortOrder)
            {
                case "name_desc":
                    users = users.OrderByDescending(u => u.u_firstName);
                    break;
                default:  // Name ascending 
                    users = users.OrderBy(u => u.u_firstName);
                    break;
            }

            int pageSize = 8;
            int pageNumber = (page ?? 1);

            return View(users.ToPagedList(pageNumber, pageSize));
        }


        // GET: User/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            u_user u_user = db.u_user.Find(id);
            if (u_user == null)
            {
                return HttpNotFound();
            }
            return View(u_user);
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "u_username,u_firstName,u_lastName,u_password,u_email,u_dateOfBirth,u_host")] u_user u_user)
        {
            if (ModelState.IsValid)
            {
                db.u_user.Add(u_user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(u_user);
        }

        // GET: User/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            u_user u_user = db.u_user.Find(id);
            if (u_user == null)
            {
                return HttpNotFound();
            }
            return View(u_user);
        }

        // POST: User/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "u_username,u_firstName,u_lastName,u_password,u_email,u_dateOfBirth,u_host")] u_user u_user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(u_user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(u_user);
        }

        // GET: User/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            u_user u_user = db.u_user.Find(id);
            if (u_user == null)
            {
                return HttpNotFound();
            }
            return View(u_user);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            u_user u_user = db.u_user.Find(id);
            db.u_user.Remove(u_user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BookingWebApp/BookingWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - BookingApp</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BookingApp", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Hotel", "Index", "Hotel")</li>
                    <li>@Html.ActionLink("Services", "Index", "Services")</li>
                    <li>@Html.ActionLink("Users", "Index", "User")</li>
                    <li>@Html.ActionLink("Rooms", "Index", "Room")</li>
                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - BookingApp</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BookingWebApp/BookingWebApp/Views/Shared/_hotel.cshtml
@model IEnumerable<BookingWebApp.Models.h_hotel>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.h_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.h_stars)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.h_address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.h_zip)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.h_description)
        </th>
        <th>
           @Html.DisplayNameFor(model => model.d_destination.d_city)
        </th>
   

        @*<th>
            @Html.DisplayNameFor(model => model.ho_host.ho_firstname)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.h_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.h_stars)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.h_address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.h_zip)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.h_description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.d_destination.d_city)
        </td>
        <td>
     
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.ho_host.ho_firstname)
        </td>*@
        <td>


            @Html.ActionLink( "Index","rating", new { id = item.h_hotelid })|



            @Html.ActionLink("Edit", "Edit", new { id=item.h_hotelid }) |
            @Html.ActionLink("Details", "Details", new { id=item.h_hotelid }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.h_hotelid })
         
        </td>
    </tr>
}

</table>

BookingWebApp/BookingWebApp/Views/Shared/_rating.cshtml
@model IEnumerable<BookingWebApp.Models.ra_rating>




<table class="table">
    <tr>
        <th>
            Rating
        </th>
        <th>
           Comment
        </th>
        <th>
            @Html.DisplayNameFor(model => model.h_hotel.h_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.u_user.u_firstName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ra_rating1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ra_comment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.h_hotel.h_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.u_user.u_firstName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ra_ratingId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ra_ratingId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ra_ratingId })
        </td>
    </tr>
}

</table>

BookingWebApp/BookingWebApp/Views/Shared/_room.cshtml
@model IEnumerable<BookingWebApp.Models.r_room>



<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.r_beds)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.r_price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.r_description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.h_hotel.h_name)
        </th>
        <th>
          Type of room
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.r_beds)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.r_price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.r_description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.h_hotel.h_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tr_typeOfRoom.tr_type)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.r_number }) |
            @Html.ActionLink("Details", "Details", new { id=item.r_number }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.r_number })
        </td>
    </tr>
}

</table>