BookingWebApp/BookingWebApp/Controllers/HotelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookingWebApp.Models;
using PagedList;

namespace BookingWebApp.Controllers
{
    public class HotelController : Controller
    {
        private Entities7 db = new Entities7();

        // GET: Hotel
   
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
          //  ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
           
            var h_hotel = db.h_hotel.Include(h => h.d_destination).Include(h => h.ho_host);
            
            if (searchString != null)
            {
               
                page = 1;
            }
            else { searchString = currentFilter; }
            ViewBag.CurrentFilter = searchString;

            //var hotels = from h in db.h_hotel
            //             select h;
            if (!String.IsNullOrEmpty(searchString)) { h_hotel = h_hotel.Where(h => h.h_name.ToUpper().Contains(searchString.ToUpper())); }

            switch (sortOrder)
            {
                case "name_desc":
                    h_hotel = h_hotel.OrderByDescending(s => s.h_name);
                    break;
               
                
                default: // Name ascending
                    h_hotel = h_hotel.OrderBy(s => s.h_name);
                    break;
            }

            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(h_hotel.ToPagedList(pageNumber, pageSize));
        }

        // GET: Hotel/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            h_hotel h_hotel = db.h_hotel.Find(id);
            if (h_hotel == null)
            {
                return HttpNotFound();
            }
            return View(h_hotel);
        }

        // GET: Hotel/Create
        public ActionResult Create()
        {
            ViewBag.h_d_city = new SelectList(db.d_destination, "d_city", "d_city");
            ViewBag.h_ho_host = new SelectList(db.ho_host, "ho_hostname", "ho_firstname");
            return View();
        }

        // POST: Hotel/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "h_hotelid,h_name,h_stars,h_address,h_zip,h_d_city,h_description,h_d_country,h_ho_host")] h_hotel h_hotel)
        {
            if (ModelState.IsValid)
            {
                db.h_hotel.Add(h_hotel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.h_d_city = new SelectList(db.d_destination, "d_city", "d_city", h_hotel.h_d_city);
            ViewBag.h_ho_host = new SelectList(db.ho_host, "ho_hostname", "ho_firstname", h_hotel.h_ho_host);
            return View(h_hotel);
        }

        // GET: Hotel/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            h_hotel h_hotel = db.h_hotel.Find(id);
            if (h_hotel == null)
            {
                return HttpNotFound();
            }
            ViewBag.h_d_city = new SelectList(db.d_destination, "d_city", "d_city", h_hotel.h_d_city);
            ViewBag.h_ho_host = new SelectList(db.ho_host, "ho_hostname", "ho_firstname", h_hotel.h_ho_host);
            return View(h_hotel);
        }

        // POST: Hotel/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "h_hotelid,h_name,h_stars,h_address,h_zip,h_d_city,h_description,h_d_country,h_ho_host")] h_hotel h_hotel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(h_hotel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.h_d_city = new SelectList(db.d_destination, "d_city", "d_city", h_hotel.h_d_city);
            ViewBag.h_ho_host = new SelectList(db.ho_host, "ho_hostname", "ho_firstname", h_hotel.h_ho_host);
            return View(h_hotel);
        }

        // GET: Hotel/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            h_hotel h_hotel = db.h_hotel.Find(id);
            if (h_hotel == null)
            {
                return HttpNotFound();
            }
            return View(h_hotel);
        }


        // POST: Hotel/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            h_hotel h_hotel = db.h_hotel.Find(id);
            db.h_hotel.Remove(h_hotel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BookingWebApp/BookingWebApp/Views/Hotel/Create.cshtml
@model BookingWebApp.Models.h_hotel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>h_hotel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.h_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.h_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.h_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.h_stars, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.h_stars, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.h_stars, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.h_address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.h_address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.h_address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.h_zip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.h_zip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.h_zip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.h_d_city, "h_d_city", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("h_d_city", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.h_d_city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.h_description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.h_description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.h_description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.h_d_country, "h_d_country", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("h_d_country", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.h_d_country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.h_ho_host, "h_ho_host", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("h_ho_host", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.h_ho_host, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BookingWebApp/BookingWebApp/Views/Hotel/Delete.cshtml
@model BookingWebApp.Models.h_hotel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>h_hotel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.h_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.h_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.h_stars)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.h_stars)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.h_address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.h_address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.h_zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.h_zip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.h_description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.h_description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.d_destination.d_city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.d_destination.d_city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ho_host.ho_firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ho_host.ho_firstname)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BookingWebApp/BookingWebApp/Views/Hotel/Details.cshtml
@model BookingWebApp.Models.h_hotel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>h_hotel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.h_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.h_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.h_stars)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.h_stars)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.h_address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.h_address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.h_zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.h_zip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.h_description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.h_description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.d_destination.d_city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.d_destination.d_city)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.ho_host.ho_firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ho_host.ho_firstname)
        </dd>*@
       



    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.h_hotelid }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Rooms of hotel:  <br />
@Html.Partial("_room", Model.r_room)

Ratings of hotel:  <br />
@Html.Partial("_rating", Model.ra_rating)




</div>

BookingWebApp/BookingWebApp/Views/Hotel/Edit.cshtml
@model BookingWebApp.Models.h_hotel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>h_hotel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.h_hotelid)

        <div class="form-group">
            @Html.LabelFor(model => model.h_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.h_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.h_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.h_stars, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.h_stars, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.h_stars, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.h_address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.h_address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.h_address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.h_zip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.h_zip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.h_zip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.h_d_city, "h_d_city", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("h_d_city", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.h_d_city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.h_description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.h_description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.h_description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.h_d_country, "h_d_country", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("h_d_country", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.h_d_country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.h_ho_host, "h_ho_host", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("h_ho_host", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.h_ho_host, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BookingWebApp/BookingWebApp/Views/Hotel/Index.cshtml
@*@model IEnumerable<BookingWebApp.Models.h_hotel>*@
@model PagedList.IPagedList<BookingWebApp.Models.h_hotel> 
@using PagedList.Mvc; 
<link href = "~/Content/PagedList.css" rel = "stylesheet" type = "text/css" />


@{ ViewBag.Title = "Hotels";
}
<h2>Hotels</h2>


<p>
    @Html.ActionLink("Create New", "Create")
</p> @using (Html.BeginForm("Index", "Hotel", FormMethod.Get))

{ <p> Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string) <input type="submit" value="Search" /></p> }
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        
        <th>
          Stars
        </th>
        <th>
           Address
        </th>
        <th>
            ZIP
        </th>
        <th>
            Description
        </th>
        <th>
           Destination
        </th>
   

        @*<th>
            @Html.DisplayNameFor(model => model.ho_host.ho_firstname)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>


        <td>
            @Html.DisplayFor(modelItem => item.h_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.h_stars)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.h_address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.h_zip)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.h_description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.d_destination.d_city)
        </td>
        
        @*<td>
            @Html.DisplayFor(modelItem => item.ho_host.ho_firstname)
        </td>*@
        <td>


            



            @Html.ActionLink("Edit", "Edit", new { id=item.h_hotelid }) |
            @Html.ActionLink("Details", "Details", new { id=item.h_hotelid }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.h_hotelid })
         
        </td>
    </tr>
}

</table>
<br /> Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))